-- Création des tables pour EleganceApp (Derby)
-- À exécuter via ij ou tout client Derby connecté à la base Elegance1DB

-- Table des commandes
CREATE TABLE customer_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_date TIMESTAMP NOT NULL,
    total_amount DECIMAL(12,2) NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING'
);

-- Table des lignes de commande
CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES customer_orders(id) ON DELETE CASCADE
);

-- Index pour les performances (optionnel)
CREATE INDEX idx_orders_user ON customer_orders(user_id);
CREATE INDEX idx_order_items_order ON order_items(order_id);
